version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "localstack-kinesis-s3-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fe90189f"
s3_prefix = "localstack-kinesis-s3-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
